modules/program/models/ReadingPaper.php
<?php

namespace app\modules\program\models;

use Yii;
use yii\filters\AccessControl;
use app\modules\setting\models\ParliamentDetails;

/**
 * This is the model class for table "reading_paper".
 *
 * @property int $id
 * @property int $parliament_id
 * @property int $meeting_id
 * @property int $forum_id
 * @property string $meeting_header
 * @property string $context
 * @property string $date
 * @property string $minister
 * @property string $related_committee
 * @property int $order_number
 * @property string $status
 * @property int $goes_through_voting
 * @property string $win_by
 * @property int $is_read
 * @property string $read_at
 * @property int $paper_status
 * @property int $created_by
 * @property string $created_date
 */
class ReadingPaper extends \yii\db\ActiveRecord
{
    const standard_order = ['प्रधानमन्त्रीको बक्तब्य','मन्त्रीको बक्तब्य','शून्य समय','विशेष समय','प्रत्यक्ष प्रशनहरु','राष्ट्रपति','प्रधानमन्त्री तथा मन्त्रिपरिषद्को कार्यालय','राष्ट्रपतिको कार्यालय','व्यवस्थापन कार्य','समितिको प्रतिवेदन','महासन्धि','सन्धि','सम्झौता','नीति तथा कार्यक्रम','राजस्व व्ययको बार्षिक अनुमान','ध्यानाकर्षण प्रस्ताव','जरुरी सार्वजनिक महत्वको प्रस्ताव','संकल्प प्रस्ताव','स्थगन प्रस्ताव','सभामुखको निर्वाचन ','उप-सभामुखको निर्वाचन','राष्ट्रपतिको निर्वाचन','उप-राष्ट्रपतिको निर्वाचन','अनुपस्थितिको सूचना','स्थान रिक्तता','समिति गठन','संवैधानिक आयोगको प्रतिवेदन','समितिको प्रतिवेदन','समितिको बार्षिक प्रतिवेदन','शोक प्रस्ताव','समिति गठन','समितिमा थपघट तथा हेरफेर','बैठकमा अध्यक्षता गर्ने सदस्यको मनोनयन','राष्ट्रपतिबाट सम्बोधन','अन्य'];
    const aumati_magne =['_first_content','_second_content'];
    const time_template =['_discuss','_discuss_body','_second_content'];
    const bichar_gariyos_general = ['_first_content','_second_content','_discuss','_discuss_body', '_discuss_reply' ,'_decision_general'];
    const bichar_gariyos_no_discuss = ['_first_content','_decision_no_discuss'];
    const bichar_gariyos_result = ['_result_yes','_result_no','_result_overall_no','_result_overall_yes'];
    const result_nepali = ['बहुमत स्वीकृत','बहुमत अस्वीकृति','सर्बसम्ती अस्वीकृति','सर्बसम्ती स्वीकृत'];
    const letter = ['_first_content'];
    const report_reading_pages = ['_first_content'];
    const crt_bill_anumati = ['_first_content','_second_content','_third_content'];
    const anumati_bill_birod_template = ['_first_content','_second_content','_third_content','_st_decision','_st_re_back_one','_st_re_back_two','_result','_result_yes','_result_no','_st_last_content'];
    const crt_bill_bichar_garios = ['_first_content','_second_content','_discuss','_discuss_body', '_discuss_reply','_discuss_end' ,'_decision_general','_decision_no_discuss','_result','_result_yes','_result_no','_result_overall_no','_result_overall_yes'];


    const samitima_pathaiyos = ['_first_content','_second_content','_third_content', '_decision' ,'_result','_result_yes','_result_no','_result_overall_no','_result_overall_yes'];

    const dhyan_akarsan_prasthab = ['_first_content','_second_content','_third_content', '_discuss_suppoter' ,'_discuss_reply'];
    const jaruri_sarbajanik_mahato = ['_first_content', '_discuss_suppoter','_discuss','_discuss_body' ,'_discuss_reply','_st_last_content'];
    const sankalpa_prastab = ['_first_content', '_second_content', '_third_content', '_discuss_suppoter','_discuss','_discuss_body','_discuss_end' ,'_discuss_reply','_decision','_result','_result_yes','_result_no','_result_overall_yes'];
    const condolence = ['_first_content','_second_content','_third_content'];
    
    const pertibedan_puna_samitima_pathaiyos = ['_first_content','_st_discuss','_st_discuss_body','_st_reply','_st_decision','_st_result','_st_yes','_st_no','_decision_general','_general_result','_general_yes','_general_no','_second_content','_discuss','_discuss_body','_discuss_reply','_discuss_end','_decision','_decision_no_discuss','_result','_result_yes','_result_no','_pertibedan_decision','_pertibedan_result','_pertibedan_yes','_pertibedan_no','_bidhyak_decision','_bidhyak_result','_bidhyak_yes','_bidhyak_no','_prastab_first_content','_prastab_decision','_prastab_result','_prastab_yes','_prastab_no','_third_content','_final_decision','_final_result','_final_no','_final_yes'];
    const pertibedan_sahitko_chalfal = ['_first_content','_decision_general','_general_result','_general_yes','_general_no','_second_content','_discuss','_discuss_body','_discuss_reply','_discuss_end','_decision','_decision_no_discuss','_result','_result_yes','_result_no','_pertibedan_decision','_pertibedan_result','_pertibedan_yes','_pertibedan_no','_bidhyak_decision','_bidhyak_result','_bidhyak_yes','_bidhyak_no','_prastab_first_content','_prastab_decision','_prastab_result','_prastab_yes','_prastab_no','_third_content','_final_decision','_final_result','_final_no','_final_yes'];
    const ordinance_anumati = ['_first_content'];
    const suikrigarios = ['_first_content','_second_content','_decision','_result','_result_yes','_result_no','_result_overall_no','_result_overall_yes'];
    const asuikrit = ['_first_content','_second_content','_third_content','_discuss','_discuss_body', '_discuss_reply','_end_discuss','_st_decision','_st_re_back_one','_st_re_back_two','_st_result','_st_yes','_st_no','_decision_general','_decision','_result','_result_yes','_result_no'];
    const asui_sukrit_ = ['_first_content','_second_content','_decision_general','_result_yes','_result_no','_result_overall_no','_result_overall_yes'];
    const aggrement_pesh = ['_first_content'];
    const aggrement_chalfal_anumodan = ['_first_content','_second_content','_discuss','_discuss_body','_discuss_reply','_discuss_end','_decision','_decision_no_discuss','_result','_result_yes','_result_no','_result_overall_no','_result_overall_yes'];
    const billing_process = ['वितरण','अनुमति माग्ने','विचार गरियोस्','संशोधनको म्याद','दफावार छलफल समितिमा पठाइयोस्','दफावार छलफल सदनमा संशोधन सहित','दफावार छलफल सदनमा संशोधन विना','समितिको प्रतिवेदन पेश','प्रतिवेदन सहितको विधेयक समितिमा फिर्ता','पुनः समितिको प्रतिवेदन पेश','प्रतिवेदन सहित छलफल','पारित'];
    const letter_processing = ['दर्ता','वितरण','पारित'];
    const aggrement_processing = ['दर्ता','वितरण','पेश','छलफल','अनुमोदन'];
    const sympathy_processing = ['दर्ता','वितरण','पारित'];
    const bill_state = ['अनुमति माग्ने','विचार गरियोस्','संशोधनको म्याद','दफावार छलफल समितिमा पठाइयोस्','समितिको प्रतिवेदन पेश','प्रतिवेदन सहित छलफल','पारित'];
    const letter_state = ['दर्ता','पारित'];
    const aggrement_state = ['दर्ता','पेश','छलफल','अनुमोदन'];
    const samiti_bill = ['दर्ता','अनुमति माग्ने','विचार गरियोस्','संशोधनको म्याद','दफावार छलफल समितिमा पठाइयोस्','समितिको प्रतिवेदन पेश','प्रतिवेदन सहित छलफल','पारित'];
    const samiti_bina_bill = ['दर्ता','अनुमति माग्ने','विचार गरियोस्','संशोधनको म्याद','दफावार छलफल सदनमा संशोधन सहित','दफावार छलफल सदनमा संशोधन विना','पारित'];
    const report_state = ['समितिको प्रतिवेदन पेश','पारित'];
    const rule_state = ['पेश','टेबुल', 'छलफल','पारित']; // working on it
    const income_state = ['पेश','टेबुल', 'छलफल','पारित']; // working on it
    const ordinance_state = ['वितरण','पेश','अध्यादेश अस्वीकार गरियोस्','छलफल','अनुमोदन'];
    const proposal_state = ['पेश', 'छलफल','पारित'];
    const election_state = ['पेश', 'पारित'];
    const other_state = ['पेश', 'पारित'];

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'reading_paper';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['parliament_id', 'state'], 'required'],
            [['parliament_id', 'meeting_id', 'daily_paper_id', 'order_number', 'goes_through_voting', 'is_read', 'paper_status', 'created_by','primary_order','forum_id'], 'integer'],
            [['meeting_header', 'context', 'status', 'win_by','main_type','page_type'], 'string'],
            [['date', 'read_at', 'created_date', 'minister', 'related_committee', 'ministry' ], 'safe'],
            [['minister', 'related_committee', 'ministry'], 'string', 'max' => 250],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'parliament_id' => 'Parliament',
            'meeting_id' => 'Meeting',
            'daily_paper_id' => 'Daily Paper',
            'forum_id' => 'Darta',
            'main_type' => 'Maint Type',
            'meeting_header' => 'नाम',
            'state' => 'State',
            'context' => 'विवरन ',
            'date' => 'Date',
            'ministry' => 'Ministry',
            'minister' => 'Minister',
            'related_committee' => 'Related Committee',
            'order_number' => 'Order Number',
            'primary_order' => 'Primary Order',
            'status' => 'Status',
            'goes_through_voting' => 'Goes Through Voting',
            'win_by' => 'Win By',
            'is_read' => 'Is Read',
            'read_at' => 'Read At',
            'page_type' => 'Paper Type',
            'paper_status' => 'Paper Status',
            'created_by' => 'Created By',
            'created_date' => 'Created Date',
        ];
    }



    public function beforeSave($insert){
        if($this->isNewRecord){
            $this->created_by = Yii::$app->user->id;
            $this->created_date = new \yii\db\Expression('NOW()');
        }
        return parent::beforeSave($insert);
    }

    public function getMeetingDetails()
    {
        return $this->hasOne(MeetingDetails::className(), ['id' => 'meeting_id']);
    }
    public function getStatement()
    {
        return $this->hasMany(Statement::className(), ['forum_id' => 'forum_id']);
    }
    public function getParliament()
    {
        return $this->hasOne(ParliamentDetails::className(), ['id' => 'parliament_id']);
    }

}

modules/program/views/reading-paper/_all_reading_paper.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\helpers\Url;
use app\modules\setting\models\ParliamentMember;
use app\modules\program\models\ParticipateMemberDiscussion;
use app\components\UtilityFunctions;
use app\modules\program\models\ReadingPaperContent;
?>

<style type="text/css">
  @media print{
    .reading-paper-view, .print_ { display: none; }
    .print_section { display: block; }
  }
</style>
      <button onclick="print_reading_paper()" class="btn btn-primary print_">PRINT RP</button>
      <div class="row print_section">
      <div class="col-md-1"></div>
      <div class="col-md-10">
      <h4 class="text-center"><strong>READING PAPER</strong></h4>
    <?php
      if(!empty($reading_paper_list)){
        $main_sn = 1;
        foreach ($reading_paper_list as $reading_paper_s) {
          $id = $reading_paper_s->id;
        $next_page_id = array();
        $reading_content_details = ReadingPaperContent::find()->where('reading_paper_id=:reading_paper_id AND content_status=:content_status',[':reading_paper_id'=>$id, ':content_status'=>1])->orderBy(['order_'=>SORT_ASC])->all();
        if(!empty($reading_content_details)){
            foreach ($reading_content_details as $reading_content) {
                $next_page_id[] = $reading_content->id.":".$reading_content->_next_id;
            }
        }
        ?>
        <div class="row" style="font-size: 18pt; font-weight: bold;"><?= UtilityFunctions::NepaliCharacter($main_sn).".&nbsp;";?> शीर्षक/नाम : <?= $reading_paper_s->meeting_header; ?> &nbsp;&nbsp;&nbsp;&nbsp; प्रकृया : <?= $reading_paper_s->state; ?> &nbsp;&nbsp;&nbsp;&nbsp; नाम/बिवरण : <?= strip_tags(substr($reading_paper_s->context, 0, 250)); ?></strong></div>
        <?
    if(!empty($reading_content_details)){
      $sn = 1;

      foreach ($reading_content_details as $content_information) {
        $cont_id = $content_information->id;
        $multiple = $prv_id = null;
        for ($p=0; $p < sizeof($next_page_id) ; $p++) { 
            $next_page_information_ = explode(':', $next_page_id[$p]);
            $next_page_information = isset($next_page_information_[1]) ? explode(',', $next_page_information_[1]) : array();
            if($next_page_information && in_array($cont_id, $next_page_information) && sizeof($next_page_information) > 1){
              $multiple = true;
              $prv_id = isset($next_page_information_[0]) ? $next_page_information_[0] : null;
            }
        }
        $con_det = ReadingPaperContent::findOne($prv_id);
        if(empty($content_information->statement_id)){
            $participate_member_discussion = ParticipateMemberDiscussion::find()->where('meeting_id=:meeting_id  AND reading_paper_id=:reading_paper_id AND status=:status order by speech_order ASC',[':meeting_id'=>$reading_paper_s->meeting_id,':reading_paper_id'=>$content_information->reading_paper_id, ':status'=>1])->all();
        }else{
            $participate_member_discussion = ParticipateMemberDiscussion::find()->where('meeting_id=:meeting_id AND type=:type AND reading_paper_id=:reading_paper_id AND statement_id=:statement_id AND status=:status order by speech_order ASC',[':meeting_id'=>$reading_paper_s->meeting_id,':type'=>'on_topic',':reading_paper_id'=>$content_information->reading_paper_id, ':statement_id'=>$content_information->statement_id, ':status'=>1])->all();

        }
        $participate_member = $supporter_member = array();
        if(!empty($participate_member_discussion)){
            foreach ($participate_member_discussion as $prt_member) {
                $participate_member[] = $prt_member->parliament_member_id;
            }
        }
        $member_1 = isset($participate_member[0]) ? $participate_member[0] : null;
        $parliament_member = ParliamentMember::findOne($member_1);
        $first_member = $parliament_member ?  $parliament_member->member_title.' '.$parliament_member->first_name.' '.$parliament_member->last_name: null;
        $reading_content = $content_information->content;
        if($content_information && $first_member && $content_information->pages== '_discuss'){
          $reading_content = strip_tags($content_information->content).' सर्वप्रथम <STRONG>'.$first_member.' </STRONG> लाई छलफलमा भाग लिन समय दिन्छु । <br />(विधेयकमाथिको छलफलमा बोल्ने मा० सदस्यहरुको संख्या हेरी समय तोक्ने)';
        }

        if(isset($dailyPaper) && !empty($dailyPaper) && $dailyPaper->main_type =='proposal'){
            $supporter_member = explode(',', $darta_desk->suppoter);
        }

        if($content_information && $first_member && $content_information->pages== '_first_content' && $reading_paper_s->meeting_header == 'विशेष समय'){
          $reading_content = strip_tags($content_information->content.' सर्वप्रथम मा० श्री '.$first_member.' लाई बोल्न समय दिन्छु । ');
        }
        if($content_information && $first_member && $content_information->pages== '_first_content' && $reading_paper_s->meeting_header == 'शून्य समय'){
          $reading_content = strip_tags($content_information->content.' सर्वप्रथम मा० श्री '.$first_member.' लाई बोल्न समय दिन्छु । ');
        }

        if($content_information && $reading_paper_s->main_type =='proposal' && $paper == '_discuss_suppoter'){
          if($reading_paper_s->meeting_header =='जरुरी सार्वजनिक महत्वको प्रस्ताव'){
            for ($k=0; $k < sizeof($supporter_member) ; $k++) {
              $reading_content = strip_tags($content_information->content).' '.$supporter_member[$k].'लाई प्रस्तावको समर्थन गर्दै छलफलमा भाग लिन अनुमति दिन्छु ।(समय ... मिनेट) ';
            }
          }
          if($reading_paper_s->meeting_header =='संकल्प प्रस्ताव'){
            for ($l=0; $l < sizeof($supporter_member) ; $l++) {
                $reading_content = strip_tags($content_information->content.' '.$supporter_member[$l].'लाई छलफलमा भाग लिन अनुमति दिन्छु । (समय ३ मिनेट)');
            }

          }
          if($reading_paper_s->meeting_header =='ध्यानाकर्षण प्रस्ताव'){
            for ($k=0; $k < sizeof($supporter_member) ; $k++) {
              $reading_content = strip_tags($content_information->content.' '.$supporter_member[$k].'लाई स्पष्टिकरण माग गर्न अनुमति दिन्छु ।');
            }

          }
        }
        ?>
        <div class="row well" style="box-shadow: 3px 3px 3px 4px #888888;font-size: 16pt !important; text-align: justify;">
        <div class="row" style="text-align: left;">
        (<?= UtilityFunctions::NepaliNumber($sn); ?>) .</div>
          <?php

          if($content_information && $content_information->pages== '_discuss_body'){
            for ($p= 1; $p < sizeof($participate_member) ; $p++) { 
              $parliament_member_info = ParliamentMember::findOne($participate_member[$p]);
              $discuss_member_name_ = $parliament_member_info ? 'मा '.$parliament_member_info->member_title.' '.$parliament_member_info->first_name.' '.$parliament_member_info->last_name: null;
            ?>
            <div class="col-md-6">
              <?= $p; ?>. अब <?= $discuss_member_name_; ?>
            </div>
            <?php
            }
          }else{
            echo $reading_content;
          }
          if($multiple){
            ?>
            <h4 style="text-align: right;"><STRONG>OPTIONAL PAGE (<?= $con_det ? $con_det->pages : '' ;?>)</STRONG></h4>
            <?php
          }
          ?>

        </div>
        <?php
        $sn++;
      }
      }
      ?>
      <hr />
      <?php
      $main_sn++;
      }
    }
    ?>
    </div>
    <div class="col-md-1"></div>
    <br /><br />
<div class="row" style="float: right; text-align: justify; margin-right: 10px !important;">
  <?= UtilityFunctions::ActiveMahasachib(); ?> <br />
व्यवस्थापिका–संसदको महासचिव
</div>
</div>
<?php
$script = <<< JS
  $(".print_").click(function() {
    window.print();
});

JS;
$this->registerJs($script);
?>

modules/program/views/reading-paper/_discuss_member_in_bill.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use app\components\UtilityFunctions;
use kartik\tabs\TabsX;
use yii\widgets\ActiveForm;
use dosamigos\ckeditor\CKEditor;


/* @var $this yii\web\View */
/* @var $model app\modules\setting\models\MeetingDetails */

$this->title = 'Meeting Details';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="meeting-details-create">
    <h4 class="text-center"><strong><?= $title; ?></strong></h4>

        <div class="row">
            <h4 class="text-center"><strong>PARLIAMENT : <?= $meeting_detail->parliament ? $meeting_detail->parliament->name :  '' ;?></strong></h4>
            <table class="table table-striped table-bordered" style="font-weight: bold;">
                <tr><td>अधिवेशन </td><td>: <?= $meeting_detail ? $meeting_detail->adhibasen : ''; ?></td></tr>
                <tr><td>बैठक संख्या </td><td>: <?= $meeting_detail ? $meeting_detail->_meeting_number : ''; ?></td></tr>
                <tr><td>मिती </td><td>: <?= $meeting_detail ? $meeting_detail->_nepali_year.'-'.$meeting_detail->_nepali_month.'-'.$meeting_detail->_nepali_day : ''; ?></td></tr>
                <tr><td>समय </td><td>: <?= $meeting_detail ? $meeting_detail->_time : ''; ?></td></tr>
            </table>
        </div>
    <div class="row well">
    <?php $form = ActiveForm::begin([
        'action' => Yii::$app->homeUrl.'program/reading-paper/save-on-topic-member'
    ]); ?>
<br />
    <input type="hidden" name="meeting_id" value="<?= $meeting_detail->id ?>" />
    <input type="hidden" name="type" value="<?= $section; ?>" />
    <input type="hidden" name="statement_id" value="<?= $statement_id; ?>" />
    <input type="hidden" name="reading_paper_id" value="<?= $id; ?>" />
    <?php
        $content = "";
            $content .= "<table class='table table-striped table-bordered' style='border:2px solid black;'><thead>
            <th  style='border:2px solid black;'>SN.</th><th  style='border:2px solid black;'>Political Party</th><th style='border:2px solid black;'>Name</th><th style='border:2px solid black;'>Order</th><th style='border:2px solid black;'>NewOrder</th><th style='border:2px solid black;'>Statement Type</th><th style='border:2px solid black;'>Link</th></thead>";
            for ($i=0; $i < sizeof($participate_member); $i++) { 
                $member_id = isset($participate_member[$i]['member_id']) ? $participate_member[$i]['member_id'] : null;
                $sn = $i +1;
               $content .="<tr><td style='border:2px solid black;'>".$sn."</td><td style='border:2px solid black;'>".$participate_member[$i]['party']."</td><td style='border:2px solid black;'>".$participate_member[$i]['name']."</td><td style='border:2px solid black;'>".$participate_member[$i]['speech_order']."</td><td style='border:2px solid black;'><input type='number' name='neworder[".$participate_member[$i]['participate_member_id']."]' ".''."</td><td style='border:2px solid black'>".$participate_member[$i]['statement']."</td><td style='border:2px solid black;'> <a href='".Yii::$app->homeUrl."program/reading-paper/delete-participate-member-discussion/?participate_member_id=".$participate_member[$i]['participate_member_id']."&reading_id=".$participate_member[$i]['reading_id']."&statement_id=".$participate_member[$i]['statement_id']."'><i class='glyphicon glyphicon-trash'></i> </td></tr>";
            
        }
        $content .="</table>";
        $tab_menu = array();
        if(!empty($political_party)){
            $tab_menu[0]['label'] = '<i class="glyphicon glyphicon-flag"></i> Participate Member List';
            $tab_menu[0]['content'] = $content;
            $tab_menu[0]['active'] = true;
            $i = 1;
            foreach ($political_party as $party_info) {
                $tab_menu[$i]['label'] = '<i class="glyphicon glyphicon-flag"></i> '.$party_info->name;
                //$tab_menu[$i]['content'] = $content;
                $tab_menu[$i]['active'] = $i == 0 ? true : '';
                $tab_menu[$i]['linkOptions'] = ['data-url'=>\yii\helpers\Url::to(['/program/reading-paper/parliament-member/?party='.$party_info->id.'&meeting='.$meeting_detail->id.'&section='.$section.'&reading_paper_id='.$id])];
                $i++;
            }
        }

        echo TabsX::widget([
            'items'=>$tab_menu,
            'position'=>TabsX::POS_LEFT,
            'bordered'=>true,
            'encodeLabels'=>false
        ]);
    ?>

    <br />
    <div class="form-group text-center">
        <button type="submit" class="btn btn-success">SUBMIT INFORMATION</button>
    </div>
    <?php ActiveForm::end(); ?>
    </div>


</div>

modules/program/views/reading-paper/_participate_in_discuss.php
<?php

use yii\helpers\Html;
use app\components\UtilityFunctions;
use app\modules\setting\models\ParliamentMember;


/* @var $this yii\web\View */
/* @var $model app\modules\setting\models\MeetingDetails */

$this->title = 'Meeting Details';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="meeting-details-create">

    <h3 class="text-center"><strong>PARLIAMENT : <?= $meeting_detail->parliament ? $meeting_detail->parliament->name :  '' ;?></strong></h3>

    <div class="row well">

    	<div class="col-md-6">
    		<h4 class="text-center"><strong>MEETING DETAILS</strong></h4>
    		<table class="table table-striped table-bordered" style="font-weight: bold;">
                <tr><td colspan="2" class="text-center"><STRONG>व्यवस्थापिका–संसद</STRONG></td>
    			<tr><td>अधिवेशन </td><td>: <?= $meeting_detail ? $meeting_detail->aadhibasen : ''; ?></td></tr>
    			<tr><td>बैठक संख्या </td><td>: <?= $meeting_detail ? $meeting_detail->meeting_number : ''; ?></td></tr>
    			<tr><td>मिती </td><td>: <?= $meeting_detail->meeting_nepali_year.' '.UtilityFunctions::NepaliMonth($meeting_detail->meeting_nepali_month).' '.$meeting_detail->meeting_nepali_date.' गते'; ?></td></tr>
    			<tr><td>समय </td><td>: <?= $meeting_detail ? $meeting_detail->nepali_time : ''; ?></td></tr>
    		</table>
    	</div>
    	<div class="col-md-6">
    		<h4 class="text-center"><strong>PARTICIPATES MEMBERS DETAILS</strong></h4>
    		<table class="table table-striped table-bordered" style="font-weight: bold;">
            <THEAD><th>SN.</th><th>Party</th><th>Name</th><th>Speech Order</th></THEAD>
            <?php
                if(!empty($participate_member)){
                    $sn = 1;
                    foreach ($participate_member as $member_info) {
                        $member_information = ParliamentMember::find()->where(['id'=>$member_info->parliament_member_id,'status'=>'सकृय'])->one();
                        ?>
                        <tr>
                            <td><?= $sn; ?></td>
                            <td><?= $member_information && $member_information->political ? $member_information->political->name : ''; ?></td>
                            <td><?= $member_information ? $member_information->member_title.' '.$member_information->first_name.' '.$member_information->last_name : ''; ?></td>
                            <td><?= $member_info->speech_order; ?></td>
                        </tr>
                        <?php
                        $sn++;
                    }
                }
            ?>
    		</table>
    	</div>

</div>

modules/program/views/reading-paper/_party_wise_member.php
<h3 class="text-center"><STRONG><?= $party_information ? $party_information->name : '' ?></STRONG></h3>

<section class="content">   
<div class="row">
	<?php
		for ($i=0; $i < sizeof($parliament_member) ; $i++) {
			$member_id = $parliament_member[$i]['id'];
			$is_checked = in_array($parliament_member[$i]['id'], $participate_member) ? 'checked' : null;
			$order = isset($member_order[$member_id]) ? $member_order[$member_id] : null;
			?>
			<div class="col-md-4" style="box-shadow: 10px 10px 5px #888888;"><br /><span><input type="checkbox" name="member_array[]" value="<?= $parliament_member[$i]['id']; ?>" style="zoom:3" <?= $is_checked; ?> > &nbsp;&nbsp;<?= $parliament_member[$i]['name'] ? $parliament_member[$i]['name'] : ''; ?> &nbsp;&nbsp; <input type="number" name="member_order_<?= $parliament_member[$i]['id']; ?>" min="1" max="100" value="<?= $order; ?>"></span></div>
			<?php
		}
	?>
</div>
</section>